server:
  port: 8089

spring:
  rabbitmq:
    addresses: localhost:5672
    username: test
    password: test
  mail:
    host: smtp.gmail.com
    port: 587
    username: olbrachjanek@gmail.com
    password: ckqimsgoanmlnlni
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rabbit:
  mailQueueName: mail_details_queue
